export enum Category {
  Atletismo = '🏃🏻‍♂️ ATLETISMO',
  Baloncesto = '🏀 BALONCESTO',
  Ciclismo = '🚵‍♂️ CICLISMO',
  Cine = '📽️ CINE',
  Cultura = '🎭 CULTURA',
  Deporte = '🤸 DEPORTE',
  Ecuestre = '🐎 ECUESTRE',
  Educativo = '🎓 EDUCATIVO',
  Fiesta = '🎉 FESTIVO',
  Fútbol = '⚽ FÚTBOL',
  Gastronomia = '🥘 GASTRONOMÍA',
  Hoguera = '🔥 HOGUERA',
  Humor = '🤡 HUMOR',
  Infantil = '🧒 INFANTIL',
  Institutional = '🏛️ INSTITUCIONAL',
  Literatura = '📚 LITERATURA',
  Ludico = '🎲 LÚDICO',
  Música = '🎵 MÚSICA',
  Naturaleza = '🏞️ NATURALEZA',
  Navidad = '🎄 NAVIDAD',
  Religión = '⛪ RELIGIÓN',
  Salud = '🩺 SALUD',
  Social = '👨‍👨‍👧‍👦 SOCIAL',
  Taurino = '🐮 TAURINO',
  TerceraEdad = '🧓 TERCERA EDAD',
  Tradicion = '📜 TRADICIÓN',
  Viaje = '🚌 VIAJE',
}

const CATEGORIES: Category[] = [
  Category.Atletismo,
  Category.Baloncesto,
  Category.Ciclismo,
  Category.Cine,
  Category.Cultura,
  Category.Deporte,
  Category.Ecuestre,
  Category.Educativo,
  Category.Gastronomia,
  Category.Fiesta,
  Category.Fútbol,
  Category.Hoguera,
  Category.Humor,
  Category.Infantil,
  Category.Institutional,
  Category.Literatura,
  Category.Ludico,
  Category.Música,
  Category.Navidad,
  Category.Naturaleza,
  Category.Religión,
  Category.Salud,
  Category.Social,
  Category.Taurino,
  Category.TerceraEdad,
  Category.Tradicion,
  Category.Viaje,
];

export { CATEGORIES };
